extends: eslint:recommended
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 6
ecmaFeatures:
  destructuring: true
env:
  browser: true
  es6: true
plugins:
  - babel
globals:
  Mousetrap: true
rules:
  no-unused-vars: off
  no-console: off
  curly: warn
  camelcase: warn
  brace-style: [error, stroustrup]
  no-alert: error
  eqeqeq: error
  radix: error
  no-multi-spaces: error
